{% set name = "lbinstall" %}
{% set version = "2.0.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lbinstall-{{ version }}.tar.gz
  sha256: 57db55e44fcc6f1de58c6319ccc1c1ec1713a0e6989d66dafee761cdbfc91630

build:
  number: 0
  noarch: python
  entry_points:
    - lbinstall=lbinstall.LbInstall:LbInstall
    - lbyumcheck=lbinstall.LbYumConsistency:LbYumConsistency
    - lcgyumcheck=lbinstall.LCGYumConsistency:LCGYumConsistency
    - lbtarrpmcompare=lbinstall.LbRpmTarCompar:LbRpmTarCompare
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools_scm
    - six
  run:
    # Python 2 only
    # - backports.lzma
    - python >=3.5
    - six
    - sqlalchemy

test:
  imports:
    - lbinstall
    - lbinstall.db
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/lbinstall
  summary: LHCb package installation tool
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
