{% set name = "lbinstall" %}
{% set version = "2.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lbinstall-{{ version }}.tar.gz
  sha256: 83cfc42f8c1925748710815e9cc882b7d13b81e25ae3033faec456c611ebd4c9

build:
  entry_points:
    - lbinstall=lbinstall.LbInstall:LbInstall
    - lbyumcheck=lbinstall.LbYumConsistency:LbYumConsistency
    - lcgyumcheck=lbinstall.LCGYumConsistency:LCGYumConsistency
    - lbtarrpmcompare=lbinstall.LbRpmTarCompar:LbRpmTarCompare
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools-scm
    - six
    - pip
  run:
    - python >=3.6
    - sqlalchemy
    - six
    - zstandard

test:
  imports:
    - lbinstall
    - lbinstall.db
  commands:
    - pip check
    - lbinstall --help
    - lbyumcheck --help
    - lcgyumcheck --help
    - lbtarrpmcompare --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/lbinstall
  summary: LHCb package installation tool
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
